# Generated by Django 6.0.5 on 2026-06-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('haslo', models.CharField(max_length=128)),
                ('dostepne_dni', models.IntegerField(default=26)),
                ('pula_roczna', models.IntegerField(default=26)),
                ('czy_admin', models.BooleanField(default=False)),
                ('czy_aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wnioski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('czy_platny', models.BooleanField(default=True)),
                ('opis', models.TextField(blank=True)),
                ('data_zlozenia', models.DateTimeField(auto_now_add=True)),
                ('data_rozpatrzenia', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('zaakceptowany', 'Zaakceptowany'), ('odrzucony', 'Odrzucony')], default='oczekujacy', max_length=20)),
                ('rozpatrujacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rozpatrzone_wnioski', to='core.pracownik')),
                ('skladajacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zlozone_wnioski', to='core.pracownik')),
            ],
        ),
    ]
